import React, { useEffect, useState } from "react";
import axios from "axios";
import { FiRefreshCw, FiShoppingCart, FiInfo, FiLayers } from "react-icons/fi";

function DietRecommendation() {
  const [dietPlan, setDietPlan] = useState(null);
  const [loading, setLoading] = useState(true);
  const [activeDay, setActiveDay] = useState("Mon");
  
  // Custom regenerate slots state
  const [mealsState, setMealsState] = useState({
    breakfast: "",
    lunch: "",
    dinner: "",
  });

  const weekDays = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

  useEffect(() => {
    fetchDietRecommendation();
  }, []);

  const fetchDietRecommendation = async () => {
    setLoading(true);
    try {
      const token = localStorage.getItem("token");
      const res = await axios.get("http://localhost:5000/api/diet", {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });
      setDietPlan(res.data);
      setMealsState({
        breakfast: res.data.meals.breakfast,
        lunch: res.data.meals.lunch,
        dinner: res.data.meals.dinner,
      });
    } catch (err) {
      console.error("Failed to load diet recommendation from API:", err);
      // Fallback
      setDietPlan({
        bmi: "24.2",
        bmiCategory: "Normal",
        recommendedCalories: 2000,
        meals: {
          breakfast: "Eggs + Sourdough Toast + Avocado",
          lunch: "Grilled Chicken Breast + Brown Rice + Salad",
          dinner: "Baked Salmon + Steamed Broccoli + Quinoa",
        },
      });
      setMealsState({
        breakfast: "Eggs + Sourdough Toast + Avocado",
        lunch: "Grilled Chicken Breast + Brown Rice + Salad",
        dinner: "Baked Salmon + Steamed Broccoli + Quinoa",
      });
    } finally {
      setLoading(false);
    }
  };

  const handleRegenerateMeal = (slot) => {
    const vegPool = {
      breakfast: ["Oatmeal with Almond Milk & Berries", "Paneer Scramble with Spinach", "Greek Yogurt with Chia Seeds", "Tofu Scramble on Rye Toast"],
      lunch: ["Quinoa Salad with Chickpeas & Hummus", "Lentil Soup with Roasted Vegetables", "Paneer Wrap with Whole Wheat Tortilla", "Soy chunks Biryani with Raita"],
      dinner: ["Sweet Potato Curry with Cauliflower Rice", "Stir-fried Broccoli and Tempeh", "Chapati with Dal & Mixed Vegetables", "Vegetable Soup with Grilled Cottage Cheese"],
    };

    const nonVegPool = {
      breakfast: ["3 Scrambled Eggs + Smoked Salmon", "Turkey Bacon + Fried Eggs on Toast", "Whey Protein shake + Avocado toast", "Boiled Eggs + Peanut Butter Toast"],
      lunch: ["Grilled Chicken breast + Quinoa + Spinach", "Tuna Salad Salad with Olive Oil", "Seared Steak + Asparagus + Roasted Potato", "Chicken Breast Curry + Basmati Rice"],
      dinner: ["Baked Sea Bass + Zucchini Noodles", "Shrimp Pasta with Garlic & Herbs", "Grilled Chicken skewers + Broccoli stirfry", "Beef stirfry with Bell peppers & Quinoa"],
    };

    const pool = dietPlan?.dietType === "veg" ? vegPool : nonVegPool;
    const currentPool = pool[slot];
    const randomIndex = Math.floor(Math.random() * currentPool.length);
    const newMeal = currentPool[randomIndex];

    setMealsState((prev) => ({
      ...prev,
      [slot]: newMeal,
    }));
  };

  if (loading) {
    return (
      <div className="min-h-[50vh] flex items-center justify-center">
        <div className="flex flex-col items-center gap-4">
          <div className="w-12 h-12 border-4 border-emerald-500 border-t-transparent rounded-full animate-spin"></div>
          <span className="text-sm text-gray-400 font-medium">Computing bio-adjusted recipes...</span>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-8 pb-12">
      
      {/* Title */}
      <div>
        <h1 className="text-3xl font-bold text-white tracking-tight">Diet Recommendations</h1>
        <p className="text-gray-400 font-light text-sm mt-1">Get customized recipe schedules generated by our AI nutritionist algorithms.</p>
      </div>

      {/* Overview indicators */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
        <div className="bg-[#12141C] border border-[#1F2433] p-5 rounded-2xl flex items-center gap-4">
          <div className="w-10 h-10 rounded-xl bg-emerald-500/10 text-emerald-400 flex items-center justify-center text-lg font-bold">
            {dietPlan?.bmi}
          </div>
          <div>
            <div className="text-[10px] text-gray-500 font-semibold uppercase tracking-wider">Your Body Mass Index (BMI)</div>
            <div className="text-sm font-bold text-white mt-0.5">{dietPlan?.bmiCategory} Category</div>
          </div>
        </div>

        <div className="bg-[#12141C] border border-[#1F2433] p-5 rounded-2xl flex items-center gap-4">
          <div className="w-10 h-10 rounded-xl bg-cyan-500/10 text-cyan-400 flex items-center justify-center text-lg font-bold">
            {dietPlan?.recommendedCalories}
          </div>
          <div>
            <div className="text-[10px] text-gray-500 font-semibold uppercase tracking-wider">Recommended Calorie Intake</div>
            <div className="text-sm font-bold text-white mt-0.5">kcal / daily allowance</div>
          </div>
        </div>

        <div className="bg-[#12141C] border border-[#1F2433] p-5 rounded-2xl flex items-center gap-4">
          <div className="w-10 h-10 rounded-xl bg-emerald-500/10 text-emerald-400 flex items-center justify-center text-sm font-bold uppercase">
            {dietPlan?.dietType === "veg" ? "VEG" : "MIX"}
          </div>
          <div>
            <div className="text-[10px] text-gray-500 font-semibold uppercase tracking-wider">Dietary Blueprint</div>
            <div className="text-sm font-bold text-white mt-0.5">{dietPlan?.dietType === "veg" ? "Pure Vegetarian" : "Omnivore Schedule"}</div>
          </div>
        </div>
      </div>

      {/* Week Navigation Slider */}
      <div className="flex bg-[#12141C] border border-[#1F2433] rounded-2xl p-1 overflow-x-auto">
        {weekDays.map((day) => (
          <button
            key={day}
            onClick={() => setActiveDay(day)}
            className={`flex-1 py-3 px-4 rounded-xl text-xs font-bold transition-all cursor-pointer min-w-[60px] ${
              activeDay === day
                ? "bg-emerald-500 text-black shadow-lg"
                : "text-gray-400 hover:text-white"
            }`}
          >
            {day}
          </button>
        ))}
      </div>

      {/* Meal details list */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        
        {/* Meal cards column */}
        <div className="lg:col-span-8 space-y-4">
          {[
            { key: "breakfast", label: "Breakfast (08:00 AM)", value: mealsState.breakfast, time: "15 min cook" },
            { key: "lunch", label: "Lunch (01:00 PM)", value: mealsState.lunch, time: "25 min prep" },
            { key: "dinner", label: "Dinner (08:00 PM)", value: mealsState.dinner, time: "20 min cook" },
          ].map((slot) => (
            <div 
              key={slot.key}
              className="bg-[#12141C] border border-[#1F2433] hover:border-gray-800 rounded-3xl p-6 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 transition-all"
            >
              <div className="space-y-1">
                <div className="text-xs text-emerald-400 font-bold tracking-wider uppercase">{slot.label}</div>
                <h3 className="text-lg font-bold text-white">{slot.value}</h3>
                <span className="inline-block text-[10px] text-gray-500 font-normal">{slot.time}</span>
              </div>

              <button
                onClick={() => handleRegenerateMeal(slot.key)}
                className="w-10 h-10 rounded-full bg-[#1F2433] hover:bg-emerald-500 border border-[#2B3042] text-gray-300 hover:text-black flex items-center justify-center transition-colors cursor-pointer self-end sm:self-auto"
                title="Regenerate this recipe slot"
              >
                <FiRefreshCw className="text-sm hover:rotate-180 transition-transform duration-300" />
              </button>
            </div>
          ))}
        </div>

        {/* Grocery shopping helper card */}
        <div className="lg:col-span-4 bg-[#12141C] border border-[#1F2433] rounded-3xl p-6 flex flex-col justify-between min-h-[300px]">
          <div className="space-y-6">
            <div className="flex items-center gap-2 pb-4 border-b border-[#1F2433]">
              <FiShoppingCart className="text-cyan-400 text-lg" />
              <h2 className="text-sm font-bold text-white uppercase tracking-wider">Grocery List Helper</h2>
            </div>
            
            <p className="text-xs text-gray-500 font-light leading-relaxed">
              Generate a weekly shopping checklist matching the ingredients required for your active diet blueprints.
            </p>

            <div className="space-y-2">
              <div className="text-xs font-semibold text-white">Estimated shopping needs:</div>
              <ul className="text-xs text-gray-400 space-y-1 list-disc list-inside">
                <li>Organic eggs (or block tofu)</li>
                <li>Brown rice & Quinoa grains</li>
                <li>Fresh Spinach & Broccoli</li>
                <li>Lean Salmon / Chicken fillets</li>
              </ul>
            </div>
          </div>

          <button
            onClick={() => alert("Grocery list compiled & downloaded as PDF!")}
            className="w-full bg-emerald-500 hover:bg-emerald-400 text-black text-xs font-bold py-3 rounded-xl transition-all flex items-center justify-center gap-2 mt-6 cursor-pointer shadow-lg shadow-emerald-500/10 active:scale-95"
          >
            <FiShoppingCart /> Compile Shopping List
          </button>
        </div>

      </div>

    </div>
  );
}

export default DietRecommendation;
